### ISSUE TITLE
new installed nexe not workable?

### ISSUE THREAD

**Issue by wcc21320** [crcn/nexe#126]
My environment is ubuntu14.04 with nodejs 0.10.31. After installed nexe in global and run, it throw exception as below, I've no idea what's the json file it needed? 

$ sudo npm install nexe -g

$ nexe -i ./ -o ./bin/rc
----> checking package.json

module.js:340
    throw err;
          ^
Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.exports.package (/usr/local/lib/node_modules/nexe/lib/exe.js:632:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/nexe/bin/nexe:68:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by wcc21320** [comment]
sorry , it seems work by:
nexe -i app.js -o bin/rc

**Comment by jaredallard** [comment]
Bad error handling on my part, however that's just indication that there is no package.json for it to try to get the "main" file for!
