### ISSUE TITLE
building examples fails from the project top

### ISSUE THREAD

**Issue by jedi4ever** [crcn/nexe#20]
I can compile the examples correctly if I go into the examples/ directory.
But when stay in the top gitrepo root , when I try to compile the examples, I get some errors (for the index.js example only)

````
$ ./bin/nexe -i ./examples/hello-world/browser.js -o browser
$ ./browser
hello browser!
````

````
$ ./bin/nexe -i ./examples/hello-world/index.js -o index
$ ./index

nexe.js:0
(null)

Error: unable to load nexe
    at _require (nexe.js:12:19)
    at entries (nexe.js:29:20)
    at _require (nexe.js:14:49)
    at nexe.js:39:9
    at nexe.js:41:3
    at NativeModule.compile (node.js:619:5)
    at Function.NativeModule.require (node.js:587:18)
    at Function.Module._load (module.js:297:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
````

In the generate code I see:

`````
 define("91fddc0f/index.js", function(require, module, exports, __dirname, __filename) {
     var http = require("nexe");
     var fs = require("fs"), path = require("path"), port = 1337;
`````
The http require has been replaced by _nexe_. It seems that this sardines doing. 
It takes the name from the package.json file in the top root. (nexe)

**Comment by CKarper** [comment]
Talk about ancient.   Sardines has been replaced.  Please reopen if this is still an issue.
