### ISSUE TITLE
path join error when compiling

### ISSUE THREAD

**Issue by lukemunn** [crcn/nexe#51]
I keep getting this error when compiling. Doesn't seem to make a difference what arguments I use in my 2 line compile.js file for input, output, flags, etc.

path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at _downloadNode (/Users/lukeandkimberlee/node_modules/nexe/lib/exe.js:97:25)
    at downloadNode (/Users/lukeandkimberlee/node_modules/nexe/lib/exe.js:33:4)
    at fn (/Users/lukeandkimberlee/node_modules/async/lib/async.js:583:34)
    at Object._onImmediate (/Users/lukeandkimberlee/node_modules/async/lib/async.js:499:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)

**Comment by RainbowDashDC** [comment]
Fixed by #78.
