### ISSUE TITLE
unable to load ?

### ISSUE THREAD

**Issue by fengct** [crcn/nexe#61]
i have a project around 7 modules(files), when i got a .exe file in windows, with python2.7 and vs2012, it can't start up succeed. the error is like below:

D:\Projects\dms\dmc>dmc.exe
loading dmc...

nexe.js:12
            throw new Error("unable to load " + path);
                  ^
Error: unable to load dmc
    at _require (nexe.js:12:19)
    at module.exports (nexe.js:50:20)
    at _require (nexe.js:14:49)
    at nexe.js:2421:9
    at nexe.js:2423:3
    at NativeModule.compile (node.js:896:5)
    at Function.NativeModule.require (node.js:865:18)
    at Function.Module._load (module.js:297:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

the 'loading dmc...'  is the debug output of my dmc.js module, which appear in the first line of the js file.

**Comment by RainbowDashDC** [comment]
This is included in the latest version, so this is fixed.
