### ISSUE TITLE
Unable to package stackedit as a desktop executable app

### ISSUE THREAD

**Issue by liudonghua123** [crcn/nexe#65]
Hi, all
I downloaded the latest stackedit code and installed the dependencies and it can run without problems use node server.js.
But when I want to package it as a standalone desktop app, some problems occured, as shown below.
```
e:\code\stackedit>nexe -i server.js -o ../bin
----> downloading http://nodejs.org/dist/node-latest.tar.gz
[=====================================================================================================================]
----> Extracting the .tar.gz.
----> bundle e:\code\stackedit\server.js
cannot load "jade" in "e:\code\stackedit\node_modules\express\lib"
unable to include script e:\code\stackedit\node_modules\express\lib\application.js from e:\code\stackedit\node_modules\e
xpress\lib\express.js, Error: Cannot find module 'jade'
    at Function.module.exports [as sync] (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\n
ode_modules\amdify\node_modules\resolve\lib\sync.js:32:11)
    at resolvePath (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\node_modules\amdify\lib
\pathInfo.js:135:20)
    at self.getPathInfo (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\node_modules\amdif
y\lib\pathInfo.js:88:24)
    at C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\node_modules\amdify\lib\analyzeDeps.
js:324:13
    at C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\async\lib\async.js:111:13
    at Array.forEach (native)
    at _each (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\async\lib\async.js:32:24)
    at Object.async.each (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\async\lib\async.js:110:9)
    at scanRequired (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\node_modules\amdify\li
b\analyzeDeps.js:321:9)
    at Function.on.success.deps.forEach.dep.source (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\
sardines\node_modules\amdify\lib\analyzeDeps.js:245:5)
cannot load "../package" in "e:\code\stackedit\node_modules\express\node_modules\connect\lib"

e:\code\stackedit>
e:\code\stackedit>npm install jade
jade@1.5.0 node_modules\jade
├── character-parser@1.2.0
├── commander@2.1.0
├── mkdirp@0.5.0 (minimist@0.0.8)
├── transformers@2.1.0 (promise@2.0.0, css@1.0.8, uglify-js@2.2.5)
├── with@3.0.0 (uglify-js@2.4.15)
├── constantinople@2.0.1 (uglify-js@2.4.15)
└── monocle@1.1.51 (readdirp@0.2.5)

e:\code\stackedit>
e:\code\stackedit>
e:\code\stackedit>nexe -i server.js -o ../bin
----> bundle e:\code\stackedit\server.js
cannot load "../package" in "e:\code\stackedit\node_modules\express\node_modules\connect\lib"
unable to include script e:\code\stackedit\node_modules\express\node_modules\connect\lib\connect.js from e:\code\stacked
it\node_modules\express\node_modules\connect\index.js, Error: Cannot find module '../package'
    at Function.module.exports [as sync] (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\n
ode_modules\amdify\node_modules\resolve\lib\sync.js:32:11)
    at resolvePath (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\node_modules\amdify\lib
\pathInfo.js:135:20)
    at self.getPathInfo (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\node_modules\amdif
y\lib\pathInfo.js:88:24)
    at C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\node_modules\amdify\lib\analyzeDeps.
js:324:13
    at C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\async\lib\async.js:111:13
    at Array.forEach (native)
    at _each (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\async\lib\async.js:32:24)
    at Object.async.each (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\async\lib\async.js:110:9)
    at scanRequired (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\node_modules\amdify\li
b\analyzeDeps.js:321:9)
    at Function.on.success.deps.forEach.dep.source (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\
sardines\node_modules\amdify\lib\analyzeDeps.js:245:5)
cannot load "" in "e:\code\stackedit\node_modules\jade\node_modules\with\node_modules\uglify-js\node_modules\source-map\
node_modules\amdefine"
```
I'm new to node or nexe, can anyone help me to solve this problem, Thanks!

**Comment by LorenzGardner** [comment]
It looks like you don't have the deps installed. Notice after you manually installed jade, you got past that dep and on to the next missing one.

Try running npm install E:\code\stakedit (assuming stackedit has a package.json file).

**Comment by RainbowDashDC** [comment]
Closing due to inactivity, if you have any more questions or more info feel free to re-open!

**Comment by liudonghua123** [comment]
Sorry for no response for a long time.

I tried to remove node_modules and execute "npm install" to reinstall all of dependencies, but same error shown as before.

```
E:\code\nodejs\stackedit>npm install
grunt-contrib-copy@0.4.1 node_modules\grunt-contrib-copy

ejs@0.8.8 node_modules\ejs

grunt-bump@0.0.11 node_modules\grunt-bump
└── semver@1.1.4

grunt-string-replace@0.2.8 node_modules\grunt-string-replace
├── async@0.2.10
└── chalk@0.4.0 (ansi-styles@1.0.0, has-color@0.1.7, strip-ansi@0.1.1)

grunt-bower-task@0.3.4 node_modules\grunt-bower-task
├── colors@0.6.2
├── async@0.1.22
├── lodash@0.10.0
├── wrench@1.4.4
└── rimraf@2.0.3 (graceful-fs@1.1.14)

grunt-bower-requirejs@0.7.1 node_modules\grunt-bower-requirejs
├── slash@0.1.3
└── requirejs@2.1.16

grunt-contrib-requirejs@0.4.4 node_modules\grunt-contrib-requirejs
└── requirejs@2.1.16

grunt@0.4.5 node_modules\grunt
├── getobject@0.1.0
├── hooker@0.2.3
├── colors@0.6.2
├── dateformat@1.0.2-1.2.3
├── rimraf@2.2.8
├── async@0.1.22
├── eventemitter2@0.4.14
├── which@1.0.9
├── lodash@0.9.2
├── exit@0.1.2
├── grunt-legacy-util@0.2.0
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── coffee-script@1.3.3
├── nopt@1.0.10 (abbrev@1.0.5)
├── grunt-legacy-log@0.1.1 (lodash@2.4.1, underscore.string@2.3.3)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── findup-sync@0.1.3 (lodash@2.4.1, glob@3.2.11)
└── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)

express@3.20.1 node_modules\express
├── methods@1.1.1
├── content-type@1.0.1
├── content-disposition@0.5.0
├── range-parser@1.0.2
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── commander@2.6.0
├── vary@1.0.0
├── basic-auth@1.0.0
├── parseurl@1.3.0
├── cookie@0.1.2
├── escape-html@1.0.1
├── depd@1.0.0
├── merge-descriptors@0.0.2
├── fresh@0.2.4
├── etag@1.5.1 (crc@3.2.1)
├── proxy-addr@1.0.6 (forwarded@0.1.0, ipaddr.js@0.1.8)
├── debug@2.1.2 (ms@0.7.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── send@0.12.1 (destroy@1.0.3, ms@0.7.0, mime@1.3.4, on-finished@2.2.0)
└── connect@2.29.0 (on-headers@1.0.0, vhost@3.0.0, method-override@2.3.1, bytes@1.0.0, pause@0.0.1, response-time@2.3.0,
 serve-static@1.9.1, basic-auth-connect@1.0.0, cookie-parser@1.3.4, qs@2.3.3, finalhandler@0.3.3, morgan@1.5.1, serve-fa
vicon@2.2.0, connect-timeout@1.6.0, http-errors@1.3.1, type-is@1.6.0, body-parser@1.12.0, multiparty@3.3.2, serve-index@
1.6.2, compression@1.4.1, errorhandler@1.3.4, express-session@1.10.3, csurf@1.7.0)

grunt-contrib-less@0.7.0 node_modules\grunt-contrib-less
├── grunt-lib-contrib@0.6.1 (zlib-browserify@0.0.1)
└── less@1.4.2 (mkdirp@0.3.5, mime@1.2.11, ycssmin@1.0.1, request@2.53.0)

grunt-contrib-jshint@0.7.2 node_modules\grunt-contrib-jshint
└── jshint@2.3.0 (console-browserify@0.1.6, underscore@1.4.4, shelljs@0.1.4, minimatch@0.4.0, cli@0.4.5)

bower@1.2.8 node_modules\bower
├── retry@0.6.1
├── bower-endpoint-parser@0.2.2
├── lru-cache@2.3.1
├── graceful-fs@2.0.3
├── mkdirp@0.3.5
├── q@0.9.7
├── archy@0.0.2
├── abbrev@1.0.5
├── bower-logger@0.2.2
├── semver@2.1.0
├── stringify-object@0.1.8
├── junk@0.2.2
├── chmodr@0.1.0
├── open@0.0.5
├── rimraf@2.2.8
├── p-throttler@0.0.1
├── nopt@2.1.2
├── osenv@0.0.3
├── which@1.0.9
├── tmp@0.0.25
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── fstream-ignore@0.0.10 (inherits@2.0.1, minimatch@0.3.0)
├── chalk@0.2.1 (has-color@0.1.7, ansi-styles@0.2.0)
├── request-progress@0.3.1 (throttleit@0.0.2)
├── mout@0.7.1
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11)
├── tar@0.1.20 (inherits@2.0.1, block-stream@0.0.7)
├── sudo-block@0.2.1 (chalk@0.1.1)
├── promptly@0.2.1 (read@1.0.5)
├── fstream@0.1.31 (inherits@2.0.1, graceful-fs@3.0.5, mkdirp@0.5.0)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── bower-config@0.5.2 (mout@0.9.1, optimist@0.6.1)
├── bower-registry-client@0.1.6 (async@0.2.10, request-replay@0.2.0, bower-config@0.4.5)
├── request@2.27.0 (aws-sign@0.3.0, tunnel-agent@0.3.0, json-stringify-safe@5.0.0, oauth-sign@0.3.0, forever-agent@0.5.2
, cookie-jar@0.3.0, mime@1.2.11, qs@0.6.6, node-uuid@1.4.3, hawk@1.0.0, form-data@0.1.4, http-signature@0.10.1)
├── inquirer@0.3.5 (async@0.2.10, lodash@1.2.1, mute-stream@0.0.3, cli-color@0.2.3)
├── handlebars@1.0.12 (optimist@0.3.7, uglify-js@2.3.6)
├── decompress-zip@0.0.8 (graceful-fs@3.0.5, mkpath@0.1.0, q@1.0.1, nopt@2.2.1, touch@0.0.2, readable-stream@1.1.13, bin
ary@0.3.0)
└── update-notifier@0.1.10 (semver@2.3.2, chalk@0.4.0, request@2.53.0, configstore@0.3.2)

E:\code\nodejs\stackedit>
E:\code\nodejs\stackedit>
E:\code\nodejs\stackedit>nexe -i server.js -o ../bin
----> downloading http://nodejs.org/dist/node-latest.tar.gz
[=====================================================================================================================]
----> Extracting the .tar.gz.
----> bundle E:\code\nodejs\stackedit\server.js
cannot load "jade" in "E:\code\nodejs\stackedit\node_modules\express\lib"
unable to include script E:\code\nodejs\stackedit\node_modules\express\lib\application.js from E:\code\nodejs\stackedit\
node_modules\express\lib\express.js, Error: Cannot find module 'jade'
    at Function.module.exports [as sync] (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\n
ode_modules\amdify\node_modules\resolve\lib\sync.js:32:11)
    at resolvePath (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\node_modules\amdify\lib
\pathInfo.js:135:20)
    at self.getPathInfo (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\node_modules\amdif
y\lib\pathInfo.js:88:24)
    at C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\node_modules\amdify\lib\analyzeDeps.
js:324:13
    at C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\async\lib\async.js:111:13
    at Array.forEach (native)
    at _each (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\async\lib\async.js:32:24)
    at Object.async.each (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\async\lib\async.js:110:9)
    at scanRequired (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\sardines\node_modules\amdify\li
b\analyzeDeps.js:321:9)
    at Function.on.success.deps.forEach.dep.source (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\nexe\node_modules\
sardines\node_modules\amdify\lib\analyzeDeps.js:245:5)
cannot load "../package" in "E:\code\nodejs\stackedit\node_modules\express\node_modules\connect\lib"

E:\code\nodejs\stackedit>
```

**Comment by CKarper** [comment]
Is this with the current version of nexe?   Can you please copy the result of running 'nexe --version'.

Oh!  I see now there's a reference to sardines in your path.  You are running a quite old version of nexe.   Please update, and let us know if this problem still exists.

**Comment by RainbowDashDC** [comment]
Re opening for now. Please follow up with the above though! It's likely this has been fixed.

**Comment by liudonghua123** [comment]
I updated nexe, and now it's working. Thanks!

**Comment by CKarper** [comment]
Great news!  Thanks for letting us know. :-)
