### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by goldalworming** [crcn/nexe#67]
```javascript
----> downloading http://nodejs.org/dist/node-latest.tar.gz
[===========================================================================================]
----> tar -xf /home/arief/web/proxyekuitas/tmp/nexe/latest/node-latest.tar.gz -C /home/arief/web/proxyekuitas/tmp/nexe/latest
----> bundle /home/arief/web/proxyekuitas/index.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'coffee-script' from '/home/arief/web/proxyekuitas/node_modules/total.js'
    at /usr/local/lib/node_modules/nexe/node_modules/module-deps/node_modules/resolve/lib/async.js:50:17
    at process (/usr/local/lib/node_modules/nexe/node_modules/module-deps/node_modules/resolve/lib/async.js:119:43)
    at /usr/local/lib/node_modules/nexe/node_modules/module-deps/node_modules/resolve/lib/async.js:128:21
    at load (/usr/local/lib/node_modules/nexe/node_modules/module-deps/node_modules/resolve/lib/async.js:60:43)
    at /usr/local/lib/node_modules/nexe/node_modules/module-deps/node_modules/resolve/lib/async.js:66:22
    at /usr/local/lib/node_modules/nexe/node_modules/module-deps/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:107:15)
```

I don't use any coffescript or native library in my code

**Comment by CKarper** [comment]
At 6 months old with no further info, I'm assuming this is fixed or irrelevant.  Please reopen if this is still an issue.
