### ISSUE TITLE
Compile with socket.io-client

### ISSUE THREAD

**Issue by DimaSearch** [crcn/nexe#72]
I try compile a simple project with one file test.js and one simple line
--------

```javascript
  console.log('Hello world');
```

```
nexe -i test.js -o test.exe  
```

Compile - OK. I get correct file test.exe

I add socket.io-client and try compile again:
--------

```javascript
var client = require('socket.io-client');  
  console.log('Hello world');
```

```
nexe -i test.js -o test.exe   
```

But error occuried:
--------

```
----> bundle Z:\Temp\!\Socket.io\test.js  
----> bundle -> Z:\Temp\!\Socket.io\tmp\nexe\latest\node-v0.10.30\lib\nexe.js  
----> make  
Found ctrpp in WinSDK--will build generated files into tools/msvs/genfiles.  
{ 'target_defaults': { 'cflags': [],  
                       'default_configuration': 'Release',  
                       'defines': [],  
                       'include_dirs': [],  
                       'libraries': []},  
  'variables': { 'clang': 0,  
                 'host_arch': 'x64',  
                 'node_has_winsdk': 'true',  
                 'node_install_npm': 'true',  
                 'node_prefix': '',  
                 'node_shared_cares': 'false',  
                 'node_shared_http_parser': 'false',  
                 'node_shared_libuv': 'false',  
                 'node_shared_openssl': 'false',  
                 'node_shared_v8': 'false',  
                 'node_shared_zlib': 'false',  
                 'node_tag': '',  
                 'node_unsafe_optimizations': 0,  
                 'node_use_dtrace': 'false',  
                 'node_use_etw': 'true',  
                 'node_use_openssl': 'true',  
                 'node_use_perfctr': 'true',  
                 'node_use_systemtap': 'false',  
                 'python': 'C:\\Python27\\python.exe',  
                 'target_arch': 'ia32',  
                 'v8_enable_gdbjit': 0,  
                 'v8_no_strict_aliasing': 1,  
                 'v8_use_snapshot': 'true',  
                 'visibility': '',  
                 'want_separate_host_toolset': 1}}  
creating  config.gypi  
creating  config.mk  
Project files generated.  
  http_parser.vcxproj -> Z:\Temp\!\Socket.io\tmp\nexe\latest\node-v0.10.30\Release\lib\http_parser.lib  
  cares.vcxproj -> Z:\Temp\!\Socket.io\tmp\nexe\latest\node-v0.10.30\Release\lib\cares.lib  
  libuv.vcxproj -> Z:\Temp\!\Socket.io\tmp\nexe\latest\node-v0.10.30\Release\lib\libuv.lib  
  node_js2c  
  non-ascii value lib\nexe.js:3339:27  
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" returned with code 1. [Z:\Temp\!\Socket.io\tmp\nexe\latest\node-v0.10.30\node_js2c.vcxproj]  
  v8_base.vcxproj -> ..\..\..\..\build\Release\lib\v8_base.lib  
  zlib.vcxproj -> Z:\Temp\!\Socket.io\tmp\nexe\latest\node-v0.10.30\Release\lib\zlib.lib  
  openssl.vcxproj -> Z:\Temp\!\Socket.io\tmp\nexe\latest\node-v0.10.30\Release\lib\openssl.lib  
----> cp Z:\Temp\!\Socket.io\tmp\nexe\latest\node-v0.10.30\Release\node.exe Z:\Temp\!\Socket.io\test.exe  
undefined  
```

**Comment by LorenzGardner** [comment]
using nexe with socket.io-client ver 1.3.2 on windows, I do not encounter any bundling issues. I'm guessing that pull request #79 fixed those issues.

I do get an execution error in your example, but quite a bit different than the one you experienced (again I think cleared up by pull request #79). The issue now is that a few dependencies deep there is a package.json file that has a "broser" field that tells the make-deps that defaults resolving using browser-resolve to use broser.js instead of index.js. This results in an unresolved symbol error when attempting to use things supplied in a browser environment.

nexe should use the opt.resolve to tell make-deps not to use browser field in package.json files.

Once I make that fix, the example builds and I get a "hello world" print out.

**Comment by LorenzGardner** [comment]
I don't see how the fix #96 is related to the issue.

The original error was fixed by #79, we could close this ticket for that and open a new ticket for ignoring the "browser" field in package.json files. 

But we'll def want to make use of the opt.resolve to tell make-deps that we aren't trying to bundle for a browser.

**Comment by CKarper** [comment]
Fix #96 didn't fix this.  I must have mistyped.

**Comment by RainbowDashDC** [comment]
Re-closing because fixed by #79. A new issue should be opened for the "browser" releated bug of sorts.

**Comment by mrbigmouth** [comment]
same test.js and command.

```js
var client = require('socket.io-client');  
console.log('Hello world');
```
```bash
nexe -i test.js -o test.exe  
```

Current generate another error:

```
----> framework => nodejs
----> bundle /home_ext1/lab/node-meteor/test.js
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received { xmlhttprequest: './lib/xmlhttprequest.js' }
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at /usr/local/lib/node_modules/nexe/node_modules/resolve/lib/async.js:151:37
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

environment: ubuntu 14
nodejs version: 5.0.0
nexe version: 0.4.2
socket.io-client version: 1.3.7

If it should be ok in previous version, anyone can tell me which version should I use?

**Comment by jaredallard** [comment]
This is a recurring issue. Possibly breaking changes in node.
