### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by fresheneesz** [crcn/nexe#76]
I'm running the following script:

```
var nexe = require('nexe');

nexe.compile({
    input: 'input.js',
    output: __dirname,
    runtime: '0.10.29',
    flags: true,
    temp: __dirname
}, function(err) {
    console.error(err)
});
```

And getting the following results

```
>node nexeTest.js

path.js:204
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at _downloadNode (D:\billysFile\code\tests\node.js\node_modules\nexe\lib\exe.js:111:38)
    at downloadNode (D:\billysFile\code\tests\node.js\node_modules\nexe\lib\exe.js:36:4)
    at fn (D:\billysFile\code\tests\node.js\node_modules\nexe\node_modules\async\lib\async.js:582:34)
    at Object._onImmediate (D:\billysFile\code\tests\node.js\node_modules\nexe\node_modules\async\lib\async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

I'm on windows 8 64 bit, node v0.10.29.

**Comment by RainbowDashDC** [comment]
Fixed by #78, the initial issue report that is, if you have any other issues please open a seperate issue. Thanks!
