### ISSUE TITLE
TypeError: Cannot call method 'replace' of undefined     at checkOpts

### ISSUE THREAD

**Issue by RainbowDashDC** [crcn/nexe#99]
```javascript
isPy=options.python.replace(/\//gm, "\\"); // use windows file paths, bat
                                                            ^
TypeError: Cannot call method 'replace' of undefined
    at checkOpts (C:\Users\Jared\Desktop\examples\conditional-reqs\node_modules\nexe\lib\exe.js:42:26)
    at fn (C:\Users\Jared\Desktop\examples\conditional-reqs\node_modules\nexe\node_modules\async\lib\async.js:582:34)
    at Object._onImmediate (C:\Users\Jared\Desktop\examples\conditional-reqs\node_modules\nexe\node_modules\async\lib\async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

This is an issue with my implementation of the python flag. Posted so that It's known to be reported.

**Comment by RainbowDashDC** [comment]
Fix: `exe.js`: 

Line 40

```
if(options.python!=='python' && options.python!=="") {
```

becomes

```javascript
if(options.python!=='python' && options.python!=="" && options.python!==undefined) {
```
